apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: my-app-basic-auth
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: my-secrets
    kind: SecretStore
  target:
    name: my-app-basic-auth
  dataFrom:
    - extract:
        key: my-secrets/my-app-basic-auth
